@startuml
!include /home/sblo/Dev/Maestro/docs/workflows/internal/_shared.puml

start
:Maestro CLI Invocation;

partition "CLI / Argparse" {
    ENTRYPOINT()
    PARSE_ARGS()
    :Determine command is 'session';
}

partition "Command Router" {
    if (Command is 'session'?) then (yes)
        :Parse session subcommands;
    else (no)
        :Continue to other handlers;
    endif
}

partition "Command Router" {
    if (Subcommand provided?) then (yes)
        if (Subcommand is 'new'?) then (yes)
            :Route to handle_session_new;
        elseif (Subcommand is 'list'?) then (yes)
            :Route to handle_session_list;
        elseif (Subcommand is 'set'?) then (yes)
            :Route to handle_session_set;
        elseif (Subcommand is 'get'?) then (yes)
            :Route to handle_session_get;
        elseif (Subcommand is 'remove'?) then (yes)
            :Route to handle_session_remove;
        elseif (Subcommand is 'details'?) then (yes)
            :Route to handle_session_details;
        elseif (Subcommand is 'breadcrumbs'?) then (yes)
            :Route to handle_wsession_breadcrumbs;
        elseif (Subcommand is 'timeline'?) then (yes)
            :Route to handle_wsession_timeline;
        elseif (Subcommand is 'stats'?) then (yes)
            :Route to handle_wsession_stats;
        else (other)
            :Show session help;
            EXIT_FAIL()
        endif
    else (no)
        :Show session help;
        EXIT_FAIL()
    endif
}

partition "Session Store" {
    :Execute session operation;
    :Read/write session files;
}

partition "CLI / Argparse" {
    :Output results to stdout;
    EXIT_OK()
}

stop
@enduml